import { useState, useEffect } from 'react'
import ForecastChart from '../components/charts/ForecastChart'
import * as dashboardApi from '../api/dashboard'

export default function PollutionForecastPage() {
  const [stations, setStations] = useState([])
  const [station, setStation] = useState('')
  const [horizon, setHorizon] = useState(14)
  const [historical, setHistorical] = useState([])
  const [forecast, setForecast] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false
    async function fetchStations() {
      try {
        const list = await dashboardApi.getStations()
        if (!cancelled && Array.isArray(list) && list.length > 0) {
          setStations(list)
          setStation((s) => s || list[0].station_code)
        }
      } catch (e) {
        if (!cancelled) setError(e.message || 'Failed to load stations')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    fetchStations()
    return () => { cancelled = true }
  }, [])

  useEffect(() => {
    if (!station) return
    let cancelled = false
    setLoading(true)
    setError(null)
    Promise.all([
      dashboardApi.getTimeSeries({ station_code: station, limit: 60 }),
      dashboardApi.getForecast({ limit: Math.max(horizon, 30) }),
    ])
      .then(([series, fc]) => {
        if (cancelled) return
        setHistorical(Array.isArray(series) ? series : [])
        setForecast(Array.isArray(fc) ? fc.slice(0, horizon) : [])
      })
      .catch((e) => {
        if (!cancelled) {
          setError(e.message || 'Failed to load data')
          setHistorical([])
          setForecast([])
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => { cancelled = true }
  }, [station, horizon])

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="font-display text-2xl font-semibold text-surface-900">Pollution forecast</h1>
        <p className="text-surface-600 mt-0.5">WQI predictions 7–30 days ahead (LSTM). Continuous timeline with historical data.</p>
      </div>

      {error && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-800">
          {error}. Run preprocessing and train the LSTM model to see forecasts.
        </div>
      )}

      <div className="flex flex-wrap gap-4">
        <div>
          <label className="label">Station</label>
          <select
            value={station}
            onChange={(e) => setStation(e.target.value)}
            className="input-field w-auto min-w-[200px]"
            disabled={loading || stations.length === 0}
          >
            {stations.length === 0 && <option value="">No stations</option>}
            {stations.map((s) => (
              <option key={s.station_code} value={s.station_code}>
                {s.station_name || s.station_code}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Forecast horizon</label>
          <select
            value={horizon}
            onChange={(e) => setHorizon(Number(e.target.value))}
            className="input-field w-auto min-w-[120px]"
          >
            <option value={7}>7 days</option>
            <option value={14}>14 days</option>
            <option value={30}>30 days</option>
          </select>
        </div>
      </div>

      <div className="card">
        <h2 className="font-display font-semibold text-surface-800 mb-4">WQI forecast — continuous time series</h2>
        <p className="text-sm text-surface-500 mb-4">X-axis: daily dates (e.g. Jan 1, Jan 2…). Historical Data and Forecast Prediction share the same timeline.</p>
        {loading ? (
          <p className="text-surface-500 py-8">Loading…</p>
        ) : (
          <ForecastChart
            historical={historical.map((d) => ({ date: d.date, wqi: d.wqi ?? d.value }))}
            forecast={forecast.map((f) => (typeof f === 'number' ? { wqi: f } : { date: f?.date, wqi: f?.wqi ?? f?.value }))}
            height={340}
          />
        )}
      </div>

      <div className="card">
        <h2 className="font-display font-semibold text-surface-800 mb-2">About</h2>
        <p className="text-sm text-surface-600">
          Forecasts are generated by an LSTM model trained on historical DOE Malaysia water quality data.
          The chart shows a continuous timeline: historical WQI followed by predicted WQI from the next day.
          Use them for planning and early awareness; always consider recent conditions.
        </p>
      </div>
    </div>
  )
}
