import { useState } from 'react'
import ForecastChart from '../components/charts/ForecastChart'

const mockHistorical = [
  { date: '20 Jan', wqi: 69 },
  { date: '25 Jan', wqi: 67 },
  { date: '30 Jan', wqi: 70 },
  { date: '02 Feb', wqi: 68 },
  { date: '05 Feb', wqi: 66 },
  { date: '10 Feb', wqi: 71 },
]

const mockForecast = [
  { date: '15 Feb', wqi: 70 },
  { date: '20 Feb', wqi: 68 },
  { date: '25 Feb', wqi: 72 },
  { date: '01 Mar', wqi: 69 },
  { date: '05 Mar', wqi: 71 },
  { date: '10 Mar', wqi: 67 },
  { date: '15 Mar', wqi: 70 },
  { date: '20 Mar', wqi: 73 },
]

const mockStations = [
  { id: 'S01', name: 'Sungai Klang' },
  { id: 'S02', name: 'Sungai Gombak' },
  { id: 'S03', name: 'Sungai Pinang' },
]

export default function PollutionForecastPage() {
  const [station, setStation] = useState('S01')
  const [horizon, setHorizon] = useState(14)

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="font-display text-2xl font-semibold text-surface-900">Pollution forecast</h1>
        <p className="text-surface-600 mt-0.5">WQI predictions 7–30 days ahead (LSTM)</p>
      </div>

      <div className="flex flex-wrap gap-4">
        <div>
          <label className="label">Station</label>
          <select
            value={station}
            onChange={(e) => setStation(e.target.value)}
            className="input-field w-auto min-w-[200px]"
          >
            {mockStations.map((s) => (
              <option key={s.id} value={s.id}>{s.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Forecast horizon</label>
          <select
            value={horizon}
            onChange={(e) => setHorizon(Number(e.target.value))}
            className="input-field w-auto min-w-[120px]"
          >
            <option value={7}>7 days</option>
            <option value={14}>14 days</option>
            <option value={30}>30 days</option>
          </select>
        </div>
      </div>

      <div className="card">
        <h2 className="font-display font-semibold text-surface-800 mb-4">WQI forecast</h2>
        <ForecastChart
          historical={mockHistorical}
          forecast={horizon === 7 ? mockForecast.slice(0, 4) : horizon === 14 ? mockForecast : [...mockForecast, ...mockForecast.slice(0, 6)]}
          height={340}
        />
      </div>

      <div className="card">
        <h2 className="font-display font-semibold text-surface-800 mb-2">About</h2>
        <p className="text-sm text-surface-600">
          Forecasts are generated by an LSTM model trained on historical DOE Malaysia water quality data.
          Use them for planning and early awareness; always consider recent conditions.
        </p>
      </div>
    </div>
  )
}
